name: torch11
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.7.2
  - aom=3.5.0
  - attr=2.5.1
  - black=22.6.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=38.0.1
  - cuda=11.6.2
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=11.8.86
  - cuda-libraries=11.6.2
  - cuda-libraries-dev=11.6.2
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=11.8.87
  - cuda-runtime=11.6.2
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.6.2
  - cuda-tools=11.6.2
  - cuda-visual-tools=11.6.2
  - dbus=1.13.6
  - expat=2.5.0
  - ffmpeg=4.4.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.12.1
  - gds-tools=1.4.0.31
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - harfbuzz=5.3.0
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - jack=1.9.21
  - jasper=2.0.33
  - joblib=1.1.0
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcups=2.3.3
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcurl=7.86.0
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdb=6.2.32
  - libdeflate=1.8
  - libdrm=2.4.113
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libglu=9.0.0
  - libiconv=1.17
  - libidn2=2.3.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.47.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.4
  - libopencv=4.6.0
  - libopus=1.3.1
  - libpciaccess=0.16
  - libpng=1.6.37
  - libpq=14.5
  - libprotobuf=3.21.9
  - libsndfile=1.1.0
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libudev1=251
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libva=2.16.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpg123=1.30.2
  - mypy_extensions=0.4.3
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - ncurses=6.3
  - nettle=3.8.1
  - nsight-compute=2022.3.0.22
  - nspr=4.32
  - nss=3.78
  - numexpr=2.8.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - opencv=4.6.0
  - openh264=2.3.1
  - openssl=1.1.1q
  - p11-kit=0.24.1
  - packaging=21.3
  - pandas=1.4.4
  - pathspec=0.9.0
  - pcre2=10.37
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - platformdirs=2.5.2
  - pthread-stubs=0.4
  - pulseaudio=14.0
  - py-opencv=4.6.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pytz=2022.1
  - qt-main=5.15.6
  - readline=8.2
  - requests=2.28.1
  - scikit-learn=1.1.1
  - scipy=1.9.1
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.39.3
  - svt-av1=1.3.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tomli=2.0.1
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - typing_extensions=4.3.0
  - urllib3=1.26.12
  - wheel=0.37.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
